#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <time.h>
#include <linux/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>

#include "fat12.h"



int fid; /* global variable set by the open() function */

ssize_t read_fat_data(int fid, fat_dirent_t* in_file) {

	lseek(fid, sizeof(boot_record_t), SEEK_CUR);
	printf("%d", sizeof(boot_record_t));
	printf("%d", sizeof(in_file->name));
	if (read(fid, &(in_file->name), sizeof(in_file->name)) < 0) {
		printf("%s", strerror(errno));
	}
	printf("%s\n", in_file->name);

	printf("%d", sizeof(in_file->ext));
	if (read(fid, &(in_file->ext), sizeof(in_file->ext)) < 0) {
			printf("%s", strerror(errno));
	}
	printf("%s\n", in_file->ext);

	printf("%d", sizeof(in_file->attr));
	if (read(fid, &(in_file->attr), sizeof(in_file->attr)) < 0) {
			printf("%s", strerror(errno));
	}
	printf("%s\n", in_file->attr);


	return 0;
//   /* uint8_t     name[8];           /*  0 file name */
//    uint8_t     ext[3];            /*  8 file extension */
//    uint8_t     attr;              /* 11 attribute byte */
//    uint8_t     winnt_flags;       /* 12 case of short filename */
//    uint8_t     create_time_secs;  /* 13 creation time, milliseconds (?) */
//    uint16_t    create_time;       /* 14 creation time */
//    uint16_t    create_data;       /* 16 creation date */
//    uint16_t    last_access;       /* 18 last access date */
//    uint16_t    h_first_cluster;   /* 20 start cluster, Hi */
//    fat_file_time_t lm_time;       /* 22 time stamp */
//    fat_file_date_t lm_date;       /* 24 date stamp */
//    uint16_t    l_first_cluster;   /* 26 starting cluster number */
//    uint32_t    size;              /* 28 size of the file */

}


int main(int argc, char *argv[])
{
	fat_dirent_t floppy_input_file;
	if (argc != 2)
	{
		printf("Usage: %s <floppy_image>\n", argv[0]);
		exit(1);
	}

	// fid is file descriptor to floppy.img
	if ( (fid = open (argv[1],  O_RDWR|O_CREAT))  < 0 )
	{
		perror("Error: ");
		return -1;
	}

	
	/* See fat12.pdf for layout details */
	
	// Check if the received

	printf("%d", read_fat_data(fid, &floppy_input_file));

	// Step 1. Create floppy.img with the school solution. Read the values 
	// from the boot sector of the floppy.img and initialize boot sector
	// with those values. If you read bootsector of the floppy.img correctly,
	// the values will be:



	//	sector_size: 512 bytes
	//	sectors_per_cluster: 1 sectors
	//	reserved_sector_count: 1
	//	number_of_fats: 2
	//	number_of_dirents: 224
	//	sector_count: 2880 sectors
	//	media_type: 0xf0
	//	fat_size_sectors: 9
	//	sectors_per_track: 18
	//	nheads: 2
	//	sectors_hidden: 0
	//	sector_count_large: 0 sectors
	


	// boot_record_t boot;
    // if (read(fid, &boot, sizeof (boot)) > 0){
	 // printf("sector_size: %d\n", boot.sector_size);
	 // printf("sectors_per_cluster: %d\n", boot.sectors_per_cluster);
	 // printf("reserved_sector_count: %d\n", boot.reserved_sector_count);
	 // printf("number_of_fats: %d\n", boot.number_of_fats);
	 // printf("number_of_dirents: %d\n", boot.number_of_dirents);
	 // printf("sector_count: %d\n", boot.sector_count);
	// }
    // etc ...
	

	
	// Step 2. Zero FAT1 and FAT2 tables according to the fat12.pdf. 
	
	// Step 3. Set direntries as free according to the fat12.pdf. 
	
	// Step 4. Handle data block (e.g you can zero them or just leave 
	// untouched. What are the pros/cons?)
	
	// For steps 2-3, you can also read the sectors from the image that was 
	// generated by the school solution if not sure what should be the values.
	
	
	close(fid);
	return 0;
}

